### ISSUE TITLE
kritashellex_1.1.0.1_setup.exe infected with Win32/Fathale.B!plock

### ISSUE THREAD

**Issue by ghost** [alvinhochun/KritaShellExtension#1]
Windows Defender reports the **kritashellex_1.1.0.1_setup.exe** as infected with **Win32/Fathale.B!plock**:

https://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=Trojan%3aWin32%2fFathale.B!plock&threatid=2147709273&enterprise=0

Any idea what's going on?

**Comment by alvinhochun** [comment]
It's probably a false positive that NSIS-made installers are getting. [Someone else reported the same issue on Krita forum](https://forum.kde.org/viewtopic.php?f=281&t=132835).

For some reason I am not getting this false positive with Microsoft Security Essentials, I was under the impression that it uses the same definition database so it seems somehow weird to me.

[Here is the VIrusTotal report I get](https://virustotal.com/en/file/842302f52f729beac0b1675363c4a6b08daa3cdd52c7e5abe97f8b9d06d1b815/analysis/1462846520/). As you can see, the Microsoft engine doesn't flag the file on VirusTotal too. To verify, you should try uploading the file you have to VirusTotal too. If for some reason the file you upload appears to be different from the one I linked to, then there could be another problem that I missed.

I'll try moving away from NSIS which should solve all these NSIS-related false positives.

**Comment by ghost** [comment]
Unfortunately I've already deleted the quarantined file. The alarm was triggered only on one of my PC's so it might be a false positive, as you're saying.
